name: linter

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install Node Dependencies
        run: npm ci

      - name: Run Laravel Pint
        run: vendor/bin/pint

      - name: Run Frontend Formatter
        run: npm run format

      - name: Run Frontend Linter
        run: npm run lint
